// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzW2Kqdj9juuOHxsMjOCk9-t8dBOKamE',
    appId: '1:757452593661:web:a140cb4cc02372ab77e194',
    messagingSenderId: '757452593661',
    projectId: 'yoga-booking-app-8d38b',
    authDomain: 'yoga-booking-app-8d38b.firebaseapp.com',
    storageBucket: 'yoga-booking-app-8d38b.firebasestorage.app',
    measurementId: 'G-WF8975VGNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYNmTN2ZZXB7LI9Vw7TYt4mEGxqhn_98o',
    appId: '1:757452593661:android:1db1386fe3a02c7e77e194',
    messagingSenderId: '757452593661',
    projectId: 'yoga-booking-app-8d38b',
    storageBucket: 'yoga-booking-app-8d38b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2AZpJBkktD1YijfffJSCVmYt01oQOMk',
    appId: '1:757452593661:ios:e0d16a0f51c2fa8077e194',
    messagingSenderId: '757452593661',
    projectId: 'yoga-booking-app-8d38b',
    storageBucket: 'yoga-booking-app-8d38b.firebasestorage.app',
    iosBundleId: 'com.example.customerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2AZpJBkktD1YijfffJSCVmYt01oQOMk',
    appId: '1:757452593661:ios:e0d16a0f51c2fa8077e194',
    messagingSenderId: '757452593661',
    projectId: 'yoga-booking-app-8d38b',
    storageBucket: 'yoga-booking-app-8d38b.firebasestorage.app',
    iosBundleId: 'com.example.customerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkzW2Kqdj9juuOHxsMjOCk9-t8dBOKamE',
    appId: '1:757452593661:web:a140cb4cc02372ab77e194',
    messagingSenderId: '757452593661',
    projectId: 'yoga-booking-app-8d38b',
    authDomain: 'yoga-booking-app-8d38b.firebaseapp.com',
    storageBucket: 'yoga-booking-app-8d38b.firebasestorage.app',
    measurementId: 'G-WF8975VGNY',
  );
}
